version: '3.8'

services:
  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: "cv_storage_db"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "POSTGRES_PASSWORD"
    ports:
      - "34176:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /mnt/vdb1/cv-storage:/storage

  app:
    build: .
    ports:
      - "5011:5000"
    environment:
      SQL_ENGINE_URI: "postgresql+asyncpg://pguser:POSTGRES_PASSWORD@db/cv_storage_db"
      LOCATION: "http://host.docker.internal:5011"
      ADMIN_TOKEN: "STORAGE_ADMIN_TOKEN"
      LOCAL_FOLDER: "/storage"
      BALANCER_URL: "http://host.docker.internal:5010"
      BALANCER_TOKEN: "CLIENT_API_ADMIN_TOKEN"
      CHUNK_SIZE: 128
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data: