version: '3.8'

services:
  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: "client_api_db"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "POSTGRES_PASSWORD"
    ports:
      - "34175:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "5010:5000"
    environment:
      SQL_ENGINE_URI: "postgresql+asyncpg://pguser:POSTGRES_PASSWORD@db/client_api_db"
      ADMIN_TOKEN: "CLIENT_API_ADMIN_TOKEN"
      STORAGE_URL: "http://host.docker.internal:5011"
      STORAGE_TOKEN: "STORAGE_ADMIN_TOKEN"
      SECRET_KEY: "SECRET_KEY"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data: